version: '2'

services:
  thumbor:
    image: apsl/thumbor-multiprocess:latest
    volumes:
      - logs:/logs
      - data:/data
    container_name: thumbor
    restart: always
    networks:
      - front
      - back
    ports:
      - 8000:8000
    environment:
      - LOADER=tc_aws.loaders.s3_loader
      - SECURITY_KEY=${THUMBOR_KEY}
      - ALLOW_UNSAFE_URL=False
      - LOG_LEVEL=debug
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TC_AWS_LOADER_BUCKET=${S3_BUCKET_NAME}
      - TC_AWS_REGION=${AWS_REGION}
      - DETECTORS=['thumbor.detectors.queued_detector.queued_complete_detector', 'thumbor.detectors.face_detector', 'thumbor.detectors.feature_detector']
      - TC_AWS_ENABLE_HTTP_LOADER=True
      - TC_AWS_RESULT_STORAGE_BUCKET=${S3_BUCKET_NAME}
      - TC_AWS_RESULT_STORAGE_ROOT_PATH=result_storage
      - RESULT_STORAGE=tc_aws.result_storages.s3_storage
      - STORAGE=thumbor.storages.mixed_storage
      - MIXED_STORAGE_FILE_STORAGE=thumbor.storages.file_storage
      - REDIS_STORAGE_SERVER_HOST=redis
      - REDIS_STORAGE_SERVER_PORT=6379
      - REDIS_STORAGE_SERVER_DB=0
      - REDIS_QUEUE_SERVER_HOST=redis
      - REDIS_QUEUE_SERVER_PORT=6379
      - REDIS_QUEUE_SERVER_DB=0
      - STORAGE_EXPIRATION_SECONDS=None
      - RESULT_STORAGE_EXPIRATION_SECONDS=None
      - MIXED_STORAGE_DETECTOR_STORAGE=tc_redis.storages.redis_storage

  remotecv:
    image: apsl/remotecv:latest
    container_name: remotecv
    restart: always
    networks:
      - front
      - back
    environment:
      - REMOTECV_REDIS_HOST=redis
      - REMOTECV_REDIS_PORT=6379
      - REMOTECV_REDIS_DATABASE=0
      - REMOTECV_LOADER=remotecv_aws.loader
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_LOADER_BUCKET=${S3_BUCKET_NAME}
      - LOG_LEVEL=DEBUG

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - front
      - back

  postgres:
    image: postgres:10
    container_name: postgres
    restart: always
    volumes:
      - /var/run/postgresql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  front:
    external:
      name: traffic_front
  back:
    external:
      name: traffic_back
