version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/photo-site
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - setup_remote_docker

      - run: docker network create traffic_front
      - run: docker network create traffic_back

      # This should go into custom primary image, here's only for the sake of explanation
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       set -x
      #       curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      #       chmod +x /usr/local/bin/docker-compose

      - run: docker-compose -f dev-docker-compose.yml up -d

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
