default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: photo_site_development
  username: postgres
  password:

test:
  <<: *default
  database: photo_site_test
  username: postgres
  password:

production:
  <<: *default
  database: photo_site_production
  username: root
  password:
